---
title: "Bayesian analysis for comparing hatchling production between modified and control sectors"
output: html_notebook
---

An attempt to compare the number of observed hatchlings between modified and control regions using a Bayesian approach.

```{r}
rm(list=ls())
library(jagsUI)
library(tidyverse)
library(loo)
library(bayesplot)
library(readr)
library(ggridges)

save.fig <- T

source("Dunstan_functions.R")
# This function is also in TomosFunctions.R in tools direcotry
# needs to update this in TomosFunctions.R 2022-04-29
extract.samples.jagsUI <- function(varname, jm){
  par.names <- unlist(dimnames(jm$samples[[1]])[2])
  col.idx <- grep(varname, par.names)
  
  samples <- lapply(jm$samples, FUN = function(x) x[, col.idx])

  if (length(col.idx) > 1){
    samples.list <- list(length = length(col.idx))
    
    for (k in 1:length(col.idx)){
      samples.list[[k]] <- unlist(lapply(samples, FUN = function(x) x[,k]))
    }
    
  } else {
    samples.list <- list(unlist(samples))
  }

  return(samples.list)
}

get.samples <- function(pars, names, years, jm, n.samples){
  out.list <- vector(mode = "list", length = length(pars))
  for (k in 1:length(pars)){
    mu.samples <- extract.samples.jagsUI(pars[k], jm)
    out.list[[k]] <- data.frame(mean = unlist(mu.samples),
                                year = rep(years, each = n.samples),
                                sector = pars[k],
                                treatment = names[k])
    
  }
  
  mu.df <- do.call(rbind, out.list) #rbind(mu.samples.1.df, mu.samples.2.df)
  return(mu.df)
}

get.samples.1yr <- function(par, name, year, jm, n.samples){
  mu.samples <- extract.samples.jagsUI(par, jm)
  mu.df <- data.frame(mean = unlist(mu.samples),
                         year = year,
                         sector = par,
                         treatment = name)
  
  return(mu.df)
}

MCMC.params <- list(n.chains = 5,
                    n.samples = 100000,
                    n.burnin = 80000,
                    n.thin = 10)

n.samples <- MCMC.params$n.chains * 
  (MCMC.params$n.samples - MCMC.params$n.burnin)/MCMC.params$n.thin

# get data
# extra comma at the end so created a new variable for Apr2022
col.def <- cols(Date = col_date(format = "%m/%d/%Y"),
                Counts_100m = col_double(),
                Season = col_integer(),
                Sector = col_character(),
                Empty = col_character()) 

data.1 <- read_csv(file = "data/Hatchling_Data_v3.1_APR2022.csv",
                   col_types = col.def) %>%
  select(-Empty)

# These two need to be changed when different runs are used
Day1 <- "12-20"
Day2 <- "04-30"

# n.days <- as.numeric(as.Date(paste0("2018-", Day2)) - 
#                        as.Date(paste0("2017-", Day1)))

seasons <- unique(data.1$Season)

data.1 %>% mutate(DOSeason = as.numeric(Date - as.Date(paste0(Season, "-",
                                                              Day1)))) %>%
  na.omit() -> data.3

```

Once the data are loaded, I extract just the necessary stuff:

```{r}
sectors <- c("2014R", "2017R", "2019R", "South", 
             "2019R South", "2019R North", "2014R South", "A")

data.3 %>% filter(Sector %in% sectors) -> data.3.1

get.data <- function(y){
              
              y %>% group_by(Season) %>%
                summarise(n = n() ) %>%
                select(n) %>% as.vector() -> n

              y %>% group_by(Season) %>% 
                mutate(ID = row_number()) %>% 
                pivot_wider(names_from = "Season", 
                            names_prefix = "yr", 
                            id_cols = "ID", 
                            values_from = "Counts_100m") %>%
                select(-"ID") %>%
                as.matrix()  -> y.wide
              
              return(list(y = y,
                          y.n = n,
                          y.wide = y.wide))
}

# Reprofiled regions
ys.2014R <- get.data(data.3.1%>%filter(Sector == "2014R" | Sector == "2014R South"))
ys.2017R <- get.data(data.3.1%>%filter(Sector == "2017R"))
ys.2019R <- get.data(data.3.1%>%filter(Sector %in% 
                                         c("2019R", "2019R South")))

# Control regions
ys.South <- get.data(data.3.1%>%filter(Sector == "South" | Sector == "A"))
# ys.South.2017 <- get.data(data.3.1%>%filter(Sector == "South" | Sector == "A") %>%
#                             filter(Season > 2016))
# ys.South.2019 <- get.data(data.3.1 %>% 
#                             filter(Sector == "South" | Sector == "A") %>%
#                             filter(Season > 2018))


jags.data <- list(y2014 = log(ys.2014R$y.wide),
                  n.2014.seasons = length(pull(ys.2014R$y.n)),
                  N2014 = pull(ys.2014R$y.n),
                  y2017 = log(ys.2017R$y.wide),
                  n.2017.seasons = length(pull(ys.2017R$y.n)),
                  N2017 = pull(ys.2017R$y.n),
                  y2019 = log(ys.2019R$y.wide),
                  n.2019.seasons = length(pull(ys.2019R$y.n)),
                  N2019 = pull(ys.2019R$y.n),
                  ySouth = log(ys.South$y.wide),
                  n.South.seasons = length(pull(ys.South$y.n)),
                  NSouth = pull(ys.South$y.n))

jags.params <- c("mu2014", "sigma2014", 
                 "mu2017", "sigma2017",
                 "mu2019", "sigma2019",
                 "muSouth", "sigmaSouth",
                 "deltaMu2014", "deltaMu2017", "deltaMu2019",
                 "ratio2014", "ratio2017", "ratio2019",
                 "deviance")

jags.out.filename <- "RData/reprofile_effect_Apr2022.rds" 
if (!file.exists(jags.out.filename)){
  jm <- jags(jags.data,
             inits = NULL,
             parameters.to.save= jags.params,
             model.file = 'models/model_reprofile_comparison.txt',
             n.chains = MCMC.params$n.chains,
             n.burnin = MCMC.params$n.burnin,
             n.thin = MCMC.params$n.thin,
             n.iter = MCMC.params$n.samples,
             DIC = T, parallel=T)
  
  saveRDS(list(jags.data = jags.data,
               jags.params = jags.params,
               MCMC.params = MCMC.params,
               jags.out = jm,
               run.date = Sys.Date()),
          file = jags.out.filename)
} else {
  jags.out <- readRDS(jags.out.filename)
  jm <- jags.out$jags.out
  jags.data <- jags.out$jags.data
  
}
  


#saveRDS(jm, file = "RData/Reprofile_comparison.rds")

jm$summary %>% data.frame() %>% 
  rownames_to_column(var = "Parameter")  -> summary.df

```



```{r}
mcmc_trace(jm$samples,
           c("mu2014[1]", "mu2014[2]", "mu2014[3]",
             "mu2014[4]", "mu2014[5]", "mu2014[6]",
             "mu2014[7]"))
```

```{r}
mcmc_trace(jm$samples,
           c("deltaMu2014[1]", "deltaMu2014[2]", "deltaMu2014[3]",
             "deltaMu2014[4]", "deltaMu2014[5]", "deltaMu2014[6]",
             "deltaMu2014[7]"))
```


```{r}
mcmc_dens(jm$samples,
           c("deltaMu2014[1]", "deltaMu2014[2]", "deltaMu2014[3]",
             "deltaMu2014[4]", "deltaMu2014[5]", "deltaMu2014[6]",
             "deltaMu2014[7]"))
```


```{r}
mcmc_trace(jm$samples,
           c("mu2017[1]", "mu2017[2]", "mu2017[3]",
             "mu2017[4]"))
```


```{r}
mcmc_trace(jm$samples,
           c("deltaMu2017[1]", "deltaMu2017[2]", "deltaMu2017[3]",
             "deltaMu2017[4]"))
```


```{r}
mcmc_dens(jm$samples,
           c("deltaMu2017[1]", "deltaMu2017[2]", "deltaMu2017[3]",
             "deltaMu2017[4]"))
```


```{r}
mcmc_trace(jm$samples,
           c("mu2019[1]", "mu2019[2]", "mu2019[3]"))
```


```{r}
mcmc_trace(jm$samples,
           c("deltaMu2019[1]", "deltaMu2019[2]", "deltaMu2019[3]"))
```


```{r}
mcmc_dens(jm$samples,
           c("deltaMu2019[1]", "deltaMu2019[2]", "deltaMu2019[3]"))
```


```{r}
mcmc_dens(jm$samples, c("mu2014[1]",  "sigma2014[1]", 
                        "muSouth[1]", "sigmaSouth[1]"))
```


```{r}
mcmc_dens(jm$samples, c("mu2014[6]",  "sigma2014[6]", 
                        "muSouth[6]", "sigmaSouth[6]"))
```


```{r}
mcmc_dens(jm$samples, c("mu2017[1]",  "sigma2017[1]", 
                        "muSouth[1]", "sigmaSouth[1]"))
```


Seems like they converged alright. Compute how many of the samples were > 0 for $\delta \mu_{2014}$, $\delta \mu_{2017}$, and $\delta \mu_{2019}$.


```{r}

delta.mu.2014 <- summary.df[grep("deltaMu2014", summary.df$Parameter),]

delta.mu.2014 %>% 
  mutate(Year = seq(from = 2014, to = 2014+nrow(delta.mu.2014)-1),
         Sector = "2014R") %>%
  select(Year, Sector, X50., X2.5., X97.5., f) -> delta.mu.2014.df

delta.mu.2017 <- summary.df[grep("deltaMu2017", summary.df$Parameter),]

delta.mu.2017 %>% 
  mutate(Year = seq(from = 2017, to = 2017+nrow(delta.mu.2017)-1),
         Sector = "2017R") %>%
  select(Year, Sector, X50., X2.5., X97.5., f) -> delta.mu.2017.df

delta.mu.2019 <- summary.df[grep("deltaMu2019", summary.df$Parameter),]

delta.mu.2019 %>% 
  mutate(Year = seq(from = 2019, to = 2019+nrow(delta.mu.2019)-1),
         Sector = "2019R") %>%
  select(Year, Sector, X50., X2.5., X97.5., f) -> delta.mu.2019.df

# f is the proportion of posterior samples that have the same sign as the mean. 

delta.mu.df <- rbind(delta.mu.2014.df, delta.mu.2017.df, delta.mu.2019.df) %>%
  mutate(P_gt_0 = ifelse(X50. > 0, f, 1-f),
         n = c(jags.data$N2014, jags.data$N2017, jags.data$N2019))


p.increase <- ggplot(delta.mu.df) +
  geom_point(aes(x = Year, y = X50.)) +
  geom_errorbar(aes(x = Year, ymin = X2.5., ymax = X97.5.)) +
  facet_grid(Sector ~ .) +
  geom_text(aes(x = Year, y = 2000, label = signif(P_gt_0, digits = 3))) +
  geom_text(aes(x = Year, y = -2000, label = paste0("n = ", n))) +
  ylab("Mean + 95%CI") + xlab("") +
  labs(title = "Difference in hatchling production from the control site")

if (save.fig)
  ggsave(p.increase,
         filename = "figures/hatchling_increase.png",
         device = "png", dpi = 600)
```

```{r}
years.2014 <- 2014:2021
ratio.2014.samples <- get.samples(pars = "ratio2014", 
                             names = "2014R", 
                             years.2014, jm, n.samples)
years.2017 <- 2017:2020
ratio.2017.samples <- get.samples(pars = "ratio2017", 
                          names = "2017R", years.2017, jm, n.samples)
years.2019 <- 2019:2021
ratio.2019.samples <- get.samples(pars = "ratio2019",
                          names = "2019R", 
                          years.2019, jm, n.samples)

p.ratio.2014R <- ggplot(data = ratio.2014.samples %>% filter(mean < 10), 
       aes(x = (mean), 
           y = as.factor(year), 
           fill = treatment)) +
  geom_vline(aes(xintercept = 1.0)) +
  geom_density_ridges(bandwidth = 0.5, alpha = 0.6,
                      show.legend = FALSE) +
  xlab("Reprofile-Control Ratio") +
  ylab("") + 
  labs(title = "Hatchling production; (2014R + 2014R South)/(South + A)")

if (save.fig)
  ggsave(p.ratio.2014R, 
         filename = "figures/hatchling_production_ratio_2014R.png",
         device = "png", dpi = 600)

ratio.2014.df <- summary.df[grep("ratio2014", summary.df$Parameter),] %>%
  mutate(year = years.2014) %>%
  select(year, mean, X2.5., X50., X97.5.) %>%
  transmute(year = year,
            Median = X50.,
            LCL = X2.5.,
            UCL = X97.5.) %>%
  mutate(p.gt.1 = ratio.2014.samples %>% 
           group_by(year) %>% 
           summarize(pgt1 = sum(mean > 1)/n.samples) %>% 
           data.frame() %>%
           select(pgt1))

ratio.2017.df <- summary.df[grep("ratio2017", summary.df$Parameter),] %>%
  mutate(year = years.2017) %>%
  select(year, mean, X2.5., X50., X97.5.) %>%
  transmute(year = year,
            Median = X50.,
            LCL = X2.5.,
            UCL = X97.5.)%>%
  mutate(p.gt.1 = ratio.2017.samples %>% 
           group_by(year) %>% 
           summarize(pgt1 = sum(mean > 1)/n.samples) %>% 
           data.frame() %>%
           select(pgt1))

ratio.2019.df <- summary.df[grep("ratio2019", summary.df$Parameter),] %>%
    mutate(year = years.2019) %>%
  select(year, mean, X2.5., X50., X97.5.) %>%
  transmute(year = year,
            Median = X50.,
            LCL = X2.5.,
            UCL = X97.5.) %>%
  mutate(p.gt.1 = ratio.2019.samples %>% 
           group_by(year) %>% 
           summarize(pgt1 = sum(mean > 1)/n.samples) %>% 
           data.frame() %>%
           select(pgt1))

```

```{r}
p.ratio.2017R <- ggplot(data = ratio.2017.samples %>% filter(mean < 10), 
                        aes(x = (mean), 
                            y = as.factor(year), 
                            fill = treatment)) +
  geom_vline(aes(xintercept = 1.0)) +
  geom_density_ridges(bandwidth = 0.5, alpha = 0.6,
                      show.legend = FALSE) +
  xlab("Reprofile-Control Ratio") +
  ylab("") + 
  labs(title = "Hatchling production; 2017R/South")

if (save.fig)
  ggsave(p.ratio.2017R, 
         filename = "figures/hatchling_production_ratio_2017R.png",
         device = "png", dpi = 600)

```


```{r}
p.ratio.2019R <- ggplot(data = ratio.2019.samples %>% filter(mean < 10), 
                        aes(x = (mean), 
                            y = as.factor(year), 
                            fill = treatment)) +
  geom_vline(aes(xintercept = 1.0)) +
  
  geom_density_ridges(bandwidth = 0.5, alpha = 0.6,
                      show.legend = FALSE) +
  xlab("Reprofile-Control Ratio") +
  ylab("") + 
  labs(title = "Hatchling production; (2019R + 2019R South)/(South + A)")

if (save.fig)
  ggsave(p.ratio.2019R, 
         filename = "figures/hatchling_production_ratio_2019R.png",
         device = "png", dpi = 600)

```

```{r}
mu.South <- summary.df[grep("muSouth", summary.df$Parameter),]

mu.South %>% 
  mutate(Year = seq(from = 2014, to = 2014+nrow(mu.South)-1),
         Sector = "South") %>%
  select(Year, Sector, mean, X2.5., X97.5.) %>%
  transmute(Year = Year,
            mean = exp(mean),
            LCL = exp(X2.5.),
            UCL = exp(X97.5.),
            Sector = "South") -> mu.South.df


mu.2014 <- summary.df[grep("mu2014", summary.df$Parameter),]

mu.2014 %>% 
  mutate(Year = seq(from = 2014, to = 2014+nrow(mu.2014)-1),
         Sector = "2014R") %>%
  select(Year, Sector, mean, X2.5., X97.5.) %>%
  transmute(Year = Year,
            mean = exp(mean),
            LCL = exp(X2.5.),
            UCL = exp(X97.5.),
            Sector = "2014R") -> mu.2014.df

mu.2017 <- summary.df[grep("mu2017", summary.df$Parameter),]

mu.2017 %>% 
  mutate(Year = seq(from = 2017, to = 2017+nrow(mu.2017)-1),
         Sector = "2017R") %>%
  select(Year, Sector, mean, X2.5., X97.5.) %>%
  transmute(Year = Year,
            mean = exp(mean),
            LCL = exp(X2.5.),
            UCL = exp(X97.5.),
            Sector = "2017R") -> mu.2017.df

mu.2019 <- summary.df[grep("mu2019", summary.df$Parameter),]

mu.2019 %>% 
  mutate(Year = seq(from = 2019, to = 2019+nrow(mu.2019)-1),
         Sector = "2019R") %>%
  select(Year, Sector, mean, X2.5., X97.5., f) %>%
  transmute(Year = Year,
            mean = exp(mean),
            LCL = exp(X2.5.),
            UCL = exp(X97.5.),
            Sector = "2019R") -> mu.2019.df

# f is the proportion of posterior samples that have the same sign as the mean. 
mu.2014.table <- left_join(mu.2014.df, mu.South.df, by = "Year") %>% 
  select(Year, mean.x, LCL.x, UCL.x, mean.y, LCL.y, UCL.y) %>%
  transmute(Year = Year,
            mean = mean.x, 
            LCL = LCL.x,
            UCL = UCL.x,
            mean.South = mean.y,
            LCL.South = LCL.y,
            UCL.South = UCL.y)
  
mu.2017.table <- left_join(mu.2017.df, mu.South.df, by = "Year") %>% 
  select(Year, mean.x, LCL.x, UCL.x, mean.y, LCL.y, UCL.y) %>%
  transmute(Year = Year,
            mean = mean.x, 
            LCL = LCL.x,
            UCL = UCL.x,
            mean.South = mean.y,
            LCL.South = LCL.y,
            UCL.South = UCL.y)

mu.2019.table <- left_join(mu.2019.df, mu.South.df, by = "Year") %>% 
  select(Year, mean.x, LCL.x, UCL.x, mean.y, LCL.y, UCL.y) %>%
  transmute(Year = Year,
            mean = mean.x, 
            LCL = LCL.x,
            UCL = UCL.x,
            mean.South = mean.y,
            LCL.South = LCL.y,
            UCL.South = UCL.y)


mu.df.figure <- rbind(mu.South.df, mu.2014.df,  
                      mu.2017.df, mu.2019.df)

ggplot(data = mu.df.figure) +
  geom_point(aes(x = Year, y = mean))+
  geom_errorbar(aes(x = Year, ymin = LCL, ymax = UCL)) +
  facet_wrap(vars(Sector))

# ggplot() +
#   geom_point(data = mu.df.figure %>% filter(Sector == "2014R"),
#              aes(x = Year, y = mean)) +
#   geom_errorbar(data = mu.df.figure %>% filter(Sector == "2014R"),
#                 aes(x = Year, ymin = LCL, ymax = UCL)) +
#   geom_point(data = mu.df.figure %>% filter(Sector == "2014R_South"),
#              aes(x = Year, y = mean),
#            color = "firebrick") +
#   geom_errorbar(data = mu.df.figure %>% filter(Sector == "2014R_South"),
#                 aes(x = Year, ymin = LCL, ymax = UCL),
#            color = "firebrick") +
#   
#   geom_point(data = mu.df.figure %>% filter(Sector == "2017R"),
#              aes(x = Year, y = mean)) +
#   geom_errorbar(data = mu.df.figure %>% filter(Sector == "2017R"),
#                 aes(x = Year, ymin = LCL, ymax = UCL)) +
#   geom_point(data = mu.df.figure %>% filter(Sector == "2017R_South"),
#              aes(x = Year, y = mean),
#            color = "firebrick") +
#   geom_errorbar(data = mu.df.figure %>% filter(Sector == "2017R_South"),
#                 aes(x = Year, ymin = LCL, ymax = UCL),
#            color = "firebrick") +
#   
#   geom_point(data = mu.df.figure %>% filter(Sector == "2019R"),
#              aes(x = Year, y = mean)) +
#   geom_errorbar(data = mu.df.figure %>% filter(Sector == "2019R"),
#                 aes(x = Year, ymin = LCL, ymax = UCL)) +
#   geom_point(data = mu.df.figure %>% filter(Sector == "2019R_South"),
#              aes(x = Year, y = mean),
#            color = "firebrick") +
#   geom_errorbar(data = mu.df.figure %>% filter(Sector == "2019R_South"),
#                 aes(x = Year, ymin = LCL, ymax = UCL),
#            color = "firebrick") +
#   facet_wrap(vars(Reprofile)) +
#   xlab("")
  

```


Ridge plots for each year

```{r}
mu.Control.sample <- get.samples(pars = "muSouth", 
                                 names = "Control", 
                                 years.2014, jm, n.samples)
# 2014
mu.2014.sample <- get.samples(c("mu2014"), 
                          c("Reprofile"), 
                          years.2014, jm, n.samples)
mu.2017.sample <- get.samples(c("mu2017"), 
                          c("Reprofile"), 
                          years.2017, jm, n.samples)
mu.2019.sample <- get.samples(c("mu2019"), 
                          c("Reprofile"), 
                          years.2019, jm, n.samples)

mu.all <- rbind(mu.2014.sample, mu.2017.sample, mu.2019.sample)

#           color = factor(reprofile),
#           point_color = reprofile, 

p.2014R <- ggplot(data = rbind(mu.2014.sample %>% filter(mean < 8.5),
                               mu.Control.sample %>% filter(mean < 8.5)),
                  aes(x = (exp(mean)), 
                      y = as.factor(year), 
                      fill = treatment)) +
  geom_density_ridges(bandwidth = 0.5, alpha = 0.6) +
  theme(legend.title = element_blank(),
        legend.position = c(0.9, 0.9)) +
  xlim(c(0, 4000)) +
  xlab("Hatchling production per sector") +
  ylab("") + 
  labs(title = "Hatchling production; (2014R + 2014R South) vs. (South + A)")

if (save.fig)
  ggsave(p.2014R, 
         filename = "figures/hatchling_production_2014R.png",
         device = "png", dpi = 600)
```

```{r}
p.2017R <- ggplot(data = rbind(mu.2017.sample %>% filter(mean < 8.5),
                               mu.Control.sample %>% filter(mean < 8.5)) %>%
                    filter(year %in% c(2017, 2018, 2019, 2020)), 
                  aes(x = (exp(mean)), 
                      y = as.factor(year), 
                      fill = treatment)) +
  geom_density_ridges(bandwidth = 0.5, alpha = 0.6) +
  theme(legend.title = element_blank(),
        legend.position = c(0.9, 0.9)) +
    xlim(c(0, 4000)) +
  xlab("Hatchling production per sector") +
  ylab("") + 
  labs(title = "Hatchling production; 2017R vs. (South + A)")

if (save.fig)
  ggsave(p.2017R,
         filename = "figures/hatchling_production_2017R.png",
         device = "png", dpi = 600)
```

```{r}
p.2019R <- ggplot(data = rbind(mu.2019.sample %>% filter(mean < 8.5),
                               mu.Control.sample %>% filter(mean < 8.5)) %>%
                    filter(year %in% c(2019, 2020, 2021)), 
       aes(x = (exp(mean)), 
           y = as.factor(year), 
           fill = treatment)) +
  geom_density_ridges(bandwidth = 0.5, alpha = 0.6) +
  xlim(c(0, 4000)) +
  theme(legend.title = element_blank(),
        legend.position = c(0.9, 0.9)) +
  xlab("Hatchling production per sector") +
  ylab("") + 
  labs(title = "Hatchling production; (2019R + 2019R South) vs. (South + A)")

if (save.fig)
  ggsave(p.2019R,
         filename = "figures/hatchling_production_2019R.png",
         device = "png", dpi = 600)
```


